apiVersion: v1
kind: Pod
metadata: 
  name: my-Pod
  lables:
    app: mypod
  namespace: work
spec: 
  containers: 
    - name: my-containers
      image: nginx
      ports:
        - containersPort: 80
      startupProbe:
        exec: 
          command: ["cat >> file1"]
        failureThreshold: 3
        successThreshold: 1
        initialDelaySeconds: 5
      livenessProbe:
        httpGet:
          path: /
          port: 80
        successThreshold: 1
        initialDelaySeconds: 5
        failureThreshold: 3
      readinessProbe: 
        port: 8080
        initialDelaySeconds: 5
        failureThreshold: 3
        successThreshold: 1
